import type { Teacher } from "@/types/teacher"

export const mockTeachers: Teacher[] = [
  {
    id: "1",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@school.edu",
    phone: "+1 (555) 123-4567",
    subject: "Mathematics",
    department: "Science",
    experience: 8,
    qualification: "M.Sc Mathematics",
    joinDate: "2020-08-15",
    status: "active",
    salary: 65000,
    address: {
      street: "123 Oak Street",
      city: "Springfield",
      state: "IL",
      zipCode: "62701",
    },
  },
  {
    id: "2",
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@school.edu",
    phone: "+1 (555) 234-5678",
    subject: "Physics",
    department: "Science",
    experience: 12,
    qualification: "Ph.D Physics",
    joinDate: "2018-01-10",
    status: "active",
    salary: 72000,
    address: {
      street: "456 Pine Avenue",
      city: "Springfield",
      state: "IL",
      zipCode: "62702",
    },
  },
  {
    id: "3",
    firstName: "Emily",
    lastName: "Rodriguez",
    email: "emily.rodriguez@school.edu",
    phone: "+1 (555) 345-6789",
    subject: "English Literature",
    department: "Arts",
    experience: 6,
    qualification: "M.A English",
    joinDate: "2021-09-01",
    status: "active",
    salary: 58000,
    address: {
      street: "789 Maple Drive",
      city: "Springfield",
      state: "IL",
      zipCode: "62703",
    },
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Thompson",
    email: "david.thompson@school.edu",
    phone: "+1 (555) 456-7890",
    subject: "History",
    department: "Social Studies",
    experience: 15,
    qualification: "M.A History",
    joinDate: "2015-08-20",
    status: "inactive",
    salary: 68000,
    address: {
      street: "321 Elm Street",
      city: "Springfield",
      state: "IL",
      zipCode: "62704",
    },
  },
  {
    id: "5",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.anderson@school.edu",
    phone: "+1 (555) 567-8901",
    subject: "Chemistry",
    department: "Science",
    experience: 10,
    qualification: "M.Sc Chemistry",
    joinDate: "2019-02-14",
    status: "active",
    salary: 63000,
    address: {
      street: "654 Birch Lane",
      city: "Springfield",
      state: "IL",
      zipCode: "62705",
    },
  },
  {
    id: "6",
    firstName: "James",
    lastName: "Wilson",
    email: "james.wilson@school.edu",
    phone: "+1 (555) 678-9012",
    subject: "Physical Education",
    department: "Sports",
    experience: 7,
    qualification: "B.Ed Physical Education",
    joinDate: "2022-06-01",
    status: "active",
    salary: 52000,
    address: {
      street: "987 Cedar Court",
      city: "Springfield",
      state: "IL",
      zipCode: "62706",
    },
  },
]

export const departments = ["All", "Science", "Arts", "Social Studies", "Sports"]
export const subjects = [
  "All",
  "Mathematics",
  "Physics",
  "Chemistry",
  "English Literature",
  "History",
  "Physical Education",
]
