import type { Timetable, LeaveRequest, Attendance, Performance } from "@/types/common"

export const mockTimetable: Timetable[] = [
  {
    id: "1",
    teacherId: "1",
    subject: "Mathematics",
    class: "Grade 10A",
    day: "Monday",
    startTime: "09:00",
    endTime: "10:00",
    room: "Room 101",
  },
  {
    id: "2",
    teacherId: "1",
    subject: "Mathematics",
    class: "Grade 10B",
    day: "Monday",
    startTime: "10:15",
    endTime: "11:15",
    room: "Room 101",
  },
  {
    id: "3",
    teacherId: "2",
    subject: "Physics",
    class: "Grade 11A",
    day: "Monday",
    startTime: "09:00",
    endTime: "10:00",
    room: "Lab 201",
  },
  {
    id: "4",
    teacherId: "3",
    subject: "English",
    class: "Grade 9A",
    day: "Tuesday",
    startTime: "11:30",
    endTime: "12:30",
    room: "Room 105",
  },
]

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "1",
    teacherId: "1",
    teacherName: "Sarah Johnson",
    type: "sick",
    startDate: "2024-01-15",
    endDate: "2024-01-17",
    reason: "Flu symptoms",
    status: "pending",
    appliedDate: "2024-01-14",
  },
  {
    id: "2",
    teacherId: "2",
    teacherName: "Michael Chen",
    type: "vacation",
    startDate: "2024-02-01",
    endDate: "2024-02-05",
    reason: "Family vacation",
    status: "approved",
    appliedDate: "2024-01-10",
    approvedBy: "Admin",
    approvedDate: "2024-01-12",
  },
  {
    id: "3",
    teacherId: "3",
    teacherName: "Emily Rodriguez",
    type: "personal",
    startDate: "2024-01-20",
    endDate: "2024-01-20",
    reason: "Personal appointment",
    status: "rejected",
    appliedDate: "2024-01-18",
  },
]

export const mockAttendance: Attendance[] = [
  {
    id: "1",
    teacherId: "1",
    teacherName: "Sarah Johnson",
    date: "2024-01-10",
    status: "present",
    checkInTime: "08:30",
    checkOutTime: "16:30",
    totalHours: 8,
  },
  {
    id: "2",
    teacherId: "2",
    teacherName: "Michael Chen",
    date: "2024-01-10",
    status: "late",
    checkInTime: "09:15",
    checkOutTime: "17:15",
    totalHours: 8,
  },
  {
    id: "3",
    teacherId: "3",
    teacherName: "Emily Rodriguez",
    date: "2024-01-10",
    status: "absent",
  },
]

export const mockPerformance: Performance[] = [
  {
    id: "1",
    teacherId: "1",
    teacherName: "Sarah Johnson",
    subject: "Mathematics",
    month: "December",
    year: 2023,
    studentsCount: 30,
    averageGrade: 85.5,
    attendanceRate: 96,
    feedbackScore: 4.5,
    completedLessons: 18,
    totalLessons: 20,
  },
  {
    id: "2",
    teacherId: "2",
    teacherName: "Michael Chen",
    subject: "Physics",
    month: "December",
    year: 2023,
    studentsCount: 28,
    averageGrade: 82.3,
    attendanceRate: 98,
    feedbackScore: 4.7,
    completedLessons: 19,
    totalLessons: 20,
  },
]

export const timeSlots = [
  "08:00",
  "08:30",
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
]

export const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
export const classes = [
  "Grade 9A",
  "Grade 9B",
  "Grade 10A",
  "Grade 10B",
  "Grade 11A",
  "Grade 11B",
  "Grade 12A",
  "Grade 12B",
]
export const rooms = ["Room 101", "Room 102", "Room 103", "Room 104", "Room 105", "Lab 201", "Lab 202", "Library"]
